import { stringify } from 'yaml';

import { contract, type OpenApiDocument } from './contract';
import { deriveRequestSchemas } from './derive';

export type { OpenApiDocument };

/**
 * Assemble the full OpenAPI document: the hand-authored `contract` with the
 * six valibot-derived request-body schemas injected into
 * `components.schemas`. Schemas are sorted for a stable, reviewable diff.
 *
 * This is the single assembly point shared by the generator script
 * (`npm run api:generate`) and the decode-contract test — so the test always
 * validates exactly what the script would write.
 */
export function buildOpenApiDocument(): OpenApiDocument {
	const doc = structuredClone(contract);
	const schemas: Record<string, unknown> = {
		...doc.components.schemas,
		...deriveRequestSchemas()
	};
	doc.components.schemas = Object.fromEntries(
		Object.keys(schemas)
			.sort()
			.map((name) => [name, schemas[name]])
	);
	return doc;
}

const BANNER = [
	'# GENERATED by `npm run api:generate` — do not edit by hand.',
	'#',
	'# Response and envelope schemas are hand-authored in',
	'# src/lib/server/api/contract.ts; request bodies are derived from the',
	'# valibot schemas in src/lib/schemas/ (src/lib/server/api/derive.ts).',
	'# The decode-contract test (src/lib/server/api/openapi.test.ts) guards the',
	'# envelope response schemas against the real user-context output.',
	''
].join('\n');

export function renderOpenApiYaml(): string {
	return BANNER + stringify(buildOpenApiDocument(), { lineWidth: 0 });
}
